version: '3.8'
services:
  rserve1:
    image: rserve:latest
    container_name: rserve1
    volumes:
      - ./rserve/Rserve-TXT.conf:/home/ruser/Rserve.conf
  rserve2:
    image: rserve:latest
    container_name: rserve2
    volumes:
      - ./rserve/Rserve-TXT.conf:/home/ruser/Rserve.conf

  rserve3:
    image: rserve:latest
    container_name: rserve3
    volumes:
      - ./rserve/Rserve-TXT.conf:/home/ruser/Rserve.conf

  haproxy:
    image: haproxy:latest
    container_name: haproxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./haproxy.pem:/etc/haproxy/haproxy.pem:rw
    command: >
      /bin/bash -c "
      echo `id` &&
      chown haproxy:haproxy /etc/haproxy/haproxy.pem &&
      exec haproxy -f /usr/local/etc/haproxy/haproxy.cfg
      "
    ports:
      - "8000:8000"
      - "6311:6311"
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
